files:
  - source: /_locales/en/*.json
    translation: /_locales/%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        pt-BR: pt_BR
        zh-CN: zh_CN
        zh-TW: zh_TW